[project]
name = "helloagents-en"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ddgs>=9.10.0",
    "dotenv>=0.9.9",
    "google-search-results>=2.4.2",
    "litellm>=1.81.0",
    "requests>=2.32.5",
]
